app:
  version: config master prod 6
spring:
  profiles:
    active: cluster
  application:
    name: cloud-hystrix-provider-cluster-payment
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://192.168.139.128:3306/test?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
